[build]
  base = "src/frontend"
  command = "npm run build"
  publish = "src/frontend/dist"

[dev]
  command = "npm --prefix src/frontend run dev"
  targetPort = 5173
  port = 8888
  autoLaunch = false

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
